version: '3.8'

services:
  python_app:   
    image: muthukdnl/chgpt_project:${RUN_NUMBER}
    container_name: app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5


  nginx:
    image: muthukdnl/rev_pro:${RUN_NUMBER}
    container_name: nginx    
    ports:
      - "80:80"    
    restart: always
    depends_on:
      - python_app

  db:
    image: muthukdnl/rl_db:${RUN_NUMBER}
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: