name: ci_cd_flow

on:
  push:
    branches:
      - main

env:
  aws_ip: "54.172.75.14"
  user_info: "ubuntu"

jobs:
  build_push_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name : Test Python App
        run: |
          cd python_app
          pip install pytest  
          pip install -r requirements.txt        
          python -m pytest test_app.py

      - name: Build and Push App Image
        uses: docker/build-push-action@v5
        with:
          context: ./python_app
          file: ./python_app/Dockerfile
          push: true
          tags: muthukdnl/chgpt_project:${{ github.run_number }}

  build_push_nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Nginx Image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx_app
          file: ./nginx_app/Dockerfile
          push: true
          tags: muthukdnl/rev_pro:${{ github.run_number }}

  build_push_db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Nginx Image
        uses: docker/build-push-action@v5
        with:
          context: ./db
          file: ./db/Dockerfile
          push: true
          tags: muthukdnl/rl_db:${{ github.run_number }}

  deploy:
     runs-on: ubuntu-latest
     needs: [build_push_app, build_push_nginx, build_push_db] 
     steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVTEKEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

      - name: Create Remote Directory
        run: |
          ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no ${{ env.user_info }}@${{ env.aws_ip }} "mkdir -p ~/app"
      
      - name: Create Env File
        run: |
          echo "RUN_NUMBER=${{ github.run_number }}" > .env
      
      - name: Copy Files to EC2
        run: |
          scp -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no Dockercompose.yaml ${{ env.user_info }}@${{ env.aws_ip }}:~/app/docker-compose.yml
          scp -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no .env ${{ env.user_info }}@${{ env.aws_ip }}:~/app/.env
      
      - name: Execute Docker Compose on EC2
        run: |
          ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no ${{ env.user_info }}@${{ env.aws_ip }} "
            cd ~/app
            sudo docker compose pull
            sudo docker compose up -d --remove-orphans
            sudo docker compose ps
          "
